# Generated by Django 2.1.2 on 2018-10-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='initials',
            field=models.CharField(default='testy', max_length=5, verbose_name='initals'),
            preserve_default=False,
        ),
    ]
